- name: "[Apache] Enable the Apache Service:{{ apache_service_name }}"
  ansible.builtin.service:
    name: "{{ apache_service_name }}" #removido a letra "e" do nome do serviço para testes
    state: started
    enabled: true