---
#- name: Instalar o conector Python MySQL 
#  ansible.builtin.yum:
#    name: python3-PyMySQL 
#    state: present


- name: 'Install "{{ package_name }}" package'
  package:
    name: "{{ package_name }}"
    state:  present
  