- name: Retroalimentar Incidente no ServiceNow
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vault.yml
  vars:
  tasks:
    - name: Adicionar nota de trabalho (Work Note) 
      servicenow.itsm.incident:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        number: "{{ incident_id | default(event.payload.incident_number) }}"
        state: closed
        other:
          work_notes: "[AUTOMAÇÃO EDA] O Red Hat Ansible Automation Platform encerrou o incidente."
      register: snow_update

    - name: Exibir o resultado da atualização
      ansible.builtin.debug:
        msg: "O ticket {{ incident_id }} foi encerrado no ServiceNow."
