---
- name: RAIO-X DO EXECUTION ENVIRONMENT
  hosts: all
  gather_facts: yes
  become: true
    
  tasks:
    - name: Garantir que o gestor de pacotes pip está instalado (Amazon Linux)
      ansible.builtin.debug:
        var: "{{ ansible_facts['fqdn']}}"

