---
    - name: upgrade all packages
      ansible.builtin.dnf: 
        name: "*"
        update_only: yes
        allow_downgrade: true
        state: latest  

    - name: Verificação de reboot necessária
      ansible.builtin.command: needs-restarting -r
      changed_when: false
      failed_when: false
      register: reboot_hint

    - name: Rebooting...
      ansible.builtin.reboot:
        msg: "Reboot required for updated kernel"
      when: reboot_hint.rc == 1