---
- name: Assume an AWS IAM role and run tasks
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    session_name: "AnsibleSession"
  
  tasks:
  - name: Assume the target IAM role
    amazon.aws.sts_assume_role:
      role_arn: "{{ target_role_arn }}"
      role_session_name: "{{ session_name }}"
    register: assumed_role_creds

  - name: Display credentials
    ansible.builtin.debug:
      var: assumed_role_creds
   
 
