---
- name: Get pods
  hosts: all
  connection: local
  vars:
    url_api: "{{ environment['K8S_AUTH_HOST'] }}"
    api_token: "{{ environment['K8S_AUTH_API_KEY'] }}"
  tasks:
    - name: teste
      debug:
        var: hostvars['ACM_Clusters_API_from_Amazon']  
  
    #- name: Auth to cluster
    #  ansible.builtin.command: 
    #    cmd: "oc login --token={{ api_token }} --server={{ url_api }}"

    #- name: Get pods
    #  ansible.builtin.command: "oc get pods"
    #  register: pod_list

    - name: Show the pods
      ansible.builtin.debug:
        var: pod_list
