---
- name: Assume an AWS IAM role and run tasks
  hosts: all
  become: true
  gather_facts: false
  vars:

    target_role_arn: "arn:aws:iam::727646502313:role/teste-profile"
    session_name: "AnsibleSession"

  tasks:
  - name: Assume the target IAM role
    amazon.aws.sts_assume_role:
      role_arn: "{{ target_role_arn }}"
      role_session_name: "{{ session_name }}"
    register: assumed_role_creds 


  - name: Use the assumed role credentials in a subsequent task (e.g., list S3 buckets)
    amazon.aws.s3_bucket_info:
# Pass the temporary credentials to the module
      aws_access_key: "{{ assumed_role_creds.sts_creds.access_key }}"
      aws_secret_key: "{{ assumed_role_creds.sts_creds.secret_key }}"
      security_token: "{{ assumed_role_creds.sts_creds.session_token }}"
    register: s3_buckets


  - name: Display S3 bucket info
    ansible.builtin.debug:
      var: s3_buckets.buckets