- name: Criar Namespace em Cada Cluster
  hosts: local-cluster
  gather_facts: no
  tasks:
    - name: Criar Namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: projeto-automacao
