- name: 'Start and enable "{{ service_name }}" service'
  service:
    name: "{{ service_name }}"
    state: started
    enabled: true


- name: Get the {{ service_name[:-1]}} version was installed
  command: "{{ service_name[:-1]}} --version"
  register: service_version


- name: Show package version
  ansible.builtin.debug:
    msg: "Service version: {{ service_version.stdout }}"
