[global]
index=https://artifactory.py.example.com/artifactory/api/pypi/pypi-remote/pypi
index-url=https://artifactory.py.example.com/artifactory/api/pypi/pypi-remote/simple
trusted-host=artifactory.py.example.com