---
- name: Ensure MySQL users are present.
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_user_password }}"
    column_case_sensitive: "false" 
    name: "myuser"
    host: "localhost"
    password: "{{ mysql_user_password }}"
    priv: '*.*:ALL,GRANT'
    state: "absent"
    
- name: Check if the user is removed
  mysql_query:
    login_user: "root"
    login_password: "{{ mysql_user_password }}"
    query: "SELECT User, Host FROM mysql.user WHERE User = 'myuser';"
  register: user_check
  changed_when: false
  failed_when: false

- name: Debug user removal
  debug:
    msg: "{{user_check.query_result}}"

