---
# tasks file for erase

- name: Remove Firewall Config
  import_tasks: 00-remove-firewall_config.yml
  when: ansible_facts['hostname'] == '{{group_names[0]}}' 

- name: Remove a Database
  import_tasks: 01-remove-database.yml

- name: Remove configurations
  import_tasks: 02-remove-configuring.yml

- name: Disable MySQL
  import_tasks: 03-disable-service.yml

- name: Remove MySQL
  import_tasks: 04-remove_package.yml